version: "3.9"

services:
  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    image: django-vite-app
    restart: unless-stopped
    command: gunicorn --workers=3 project.wsgi:application --bind 0.0.0.0:8000
    expose:
      - 8000
    volumes:
      - static_volume:/code/staticfiles
      - ./:/code
    environment:
      - DEBUG=False
      - DJANGO_VITE_DEV_MODE=False
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-django_db}
      POSTGRES_USER: ${POSTGRES_USER:-django_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-django_password}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  static_volume:
  postgres_data: